### ISSUE TITLE
Investigate PDF generation

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/narr-next#1]
One output of our application is as a document in MS Word format. A new requirement from the community is to export as PDF rather than MS Word - so it is more difficult to change the content after the event.

It should be possible to use the **Add 50** button to generate some entries to export.

This issue covers the export of our diary listing to a PDF document.

These are the rough requirements:
* Each line should be time, entry-type, privacy, then the rest of the enty
* A document footer should contain a central page number
* A document header should contain the ship name (use **HMS NONSUCH** for now).

The Filters box will need a new **Export PDF** button.  On clicking, the PDF should be downloaded.

PDFKit http://pdfkit.org/ is a client-side JS library for generating PDF.

**Comment by Morphexe** [comment]
While looking into solutions for this I found this package, haven't tested but it might be worth looking into.
https://github.com/eKoopmans/html2pdf

**Comment by IanMayo** [comment]
Thanks @Morphexe . I'm expecting the PDF export to be quite different to the UI rendering. It will be less graphical.  So sending plain text to pdfkit, or jsPDF (- which html2pdf is based upon) will probably be sufficient.

**Comment by IanMayo** [comment]
Here's a snippet of the legacy format:
![snippet](https://user-images.githubusercontent.com/1108513/38161035-84bb3c6e-34bf-11e8-906c-aea5ee194c67.png)

I'd like our pdf export to look like it, please.

Here are the significant changes:
* for the first entry on a new day, include the date
* the time for a each entry is in a special format:
    * two-digit day (06)
    * four-digit time, in 24 hour format (0819)
    * seconds, in slightly smaller font.
* we also need to adjust the line separation if there is a longer entry, since they currently overlap (see below)

<img width="884" alt="screen shot 2018-03-31 at 08 45 36" src="https://user-images.githubusercontent.com/1108513/38161065-f808d0e6-34bf-11e8-9750-805b4fd1a6cc.png">

**Comment by IanMayo** [comment]
Note: I believe there's some code to correctly format the date in here:
https://github.com/DeepBlueCLtd/narr-next/pull/95/files

**Comment by IanMayo** [comment]
Other PDF requests:
* 12px font
* ship name only on the front page, not every page
