### ISSUE TITLE
Deploy Array failing

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/narr-next#106]
The Deploy Array & Manoeuvre events are silently failing

**Comment by IanMayo** [comment]
@Morphexe  - just being nosey. Can you remember what was causing it to silently fail?

**Comment by Morphexe** [comment]
@IanMayo It was the Id we discussed the issue. you just tested with these two (unless there is another bug somewhere else), it was preventing any entry from being edited corrected.
