### ISSUE TITLE
Integrate deployment into build

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/narr-next#18]
Our current process includes running **npm build** on a dev machine, then deploying the compiled sources to the repo.

I *think* it would be better for the npm build to be run from the server.

If that's right - modify the travis build to include the npm build.

This repo *may* contain a strategy for publishing the app to GitHub pages: https://github.com/rafrex/spa-github-pages/

**Comment by Morphexe** [comment]
Got this done, just needs testing.
@IanMayo  You will need to setup in Travis an env variable called gitToken with the token for GitHub pages to work. Once that's set when a build is pushed to master, it will run all the tests in the solution, if they all pass it should auto deploy to Github pages, if not I might have messed on the script, but hopefully, all should just work.

**Comment by Morphexe** [comment]
I was investing a bit further, Travis Should auto deploy to gh-pages, and I also added a manual script called forces deploy, which will force the deployment of the build folder to the branch: gh-pages.

I think you need to set the gh-pages as the publishing source for the repository.
check this out : 

https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

The other solution is to use the master branch as the target branch which works as it is. I can't change this repository setting so I can't test, but I assume everything works fine as it is.

**Comment by IanMayo** [comment]
Ok, for future reference I'm following the instructions here:
https://docs.travis-ci.com/user/deployment/pages/
