### ISSUE TITLE
DOM performance

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/narr-next#41]
Our entry list may grow to many hundreds of entries.

Once we have implemented the formatted line, and the inline editors, we should analyse the DOM update performance.

**Comment by Morphexe** [comment]
@IanMayo  We can solve this by using 
[React Virtualize](https://github.com/bvaughn/react-virtualized)

**Comment by Morphexe** [comment]
So I actually tried to tackle this, and it seems I indeed succeed, it has some quirks to implement, and it was not as easy as I was expecting, but I got it working. basically, we can render thousands of rows, with a consistent performance (doesn't matter, if it's 10,100, 1000) it will only render what should be visible.

**Comment by IanMayo** [comment]
Sure - a control designed for virtual paging.

Once we've got more of the app developed I'm keen to verify that we don't have any bottlenecks on, for example:
* applying a filter
* moving a single entry from edit mode to view mode
* as the app loads, loading a large number of existing entries

**Comment by IanMayo** [comment]
Anecdotally, @shahbhumi53  has her narrative open with the auto-generator running. It has reached 2000 entries and her PC is slowing down.

That's the kind of situation where we need to learn more about where the actual bottlenecks are.
