### ISSUE TITLE
Validation of fields in popup dialog

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/narr-next#42]
@morphexe had implemented Modal dials for event buttons.

While the UI definition specifies their type, this isn't enforced.

We should enforce it.  I suspect RectJS Prop-Types may be the answer.

## Defined types

The types of field are (currently) declared here: https://github.com/DeepBlueCLtd/narr-next/blob/master/schema/schema.js#L61

Here's a copy:
````
 "enum": [ "text", "angle", "speed", "location", "distance", "octas", "wind-state", "integer", "day-night", "frequency" ]
````

Here is a breakdown of how to filter these:
* text - any text
* angle - integer between 0 and 360
* speed - floating point between 0 and 100
* location - special two-box control, the first taking a floating point from -180 to +180, the second taking a floating point from 0 to 360.
* distance - floating point between 0 and 100
* octas - drop-down list with 8 fractions, running from 1/8 to 8/8
* wind-state - drop down from 1 to 12
* integer - any integer
* day-night toggle between the two modes ("Day"/"Night")
* frequency - a positive floating point, from 0 to 500

**Comment by Morphexe** [comment]
@IanMayo  I created all of the validators for those types, they are in a custom class, and I also added unit tests to all of those.
I will work on creating the custom controls next.

**Comment by IanMayo** [comment]
PR covering this in #47
