### ISSUE TITLE
Highlight new entry on insert

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/narr-next#55]
Each time we add a new entry, the EntryList should ensure that entry is visible.

Note: it will nearly always be at the bottom of the list, so we really just have to check the bottom row is visible, if that's easier to implement.

Yes, a nice scrolling behaviour would be nice.

**Comment by IanMayo** [comment]
The convention is that it grows at the bottom.  In the future we may switch it around.  But, in the short term, "familiar is good".   So - yes, new entries go to the bottom.  But, after an update we don't go to the bottom, we stay on the current entry (just checking...)

**Comment by Morphexe** [comment]
Added highlighting, and simple entry animation.
Check it out if its what you want, I will improve the animation.
