### ISSUE TITLE
Only store entries in PouchDb

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/narr-next#57]
Our redux integration means that we pipe all Redux actions to PouchDb.

But, really, we only need ADD_ENTRY or UPDATE_ENTRY actions.

The others don't need to be persisted.

**Comment by Morphexe** [comment]
@IanMayo  I think we would also benefit from saving ui.state like (Is expanded or not).
But its just a matter of removing the persist function in the reducers :) I will work on it
