### ISSUE TITLE
Keep history of edits

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/narr-next#70]
There is strong value in keeping the past history of edits/updates.

CouchDb has a strategy for doing this. We can copy this strategy:

* V1. We store the document (entry)
* V2. We receive instruction to update. We see if there is a child **Versions** property.  There isn't. We take copy of old version. We replace it entry with new one.  We insert old version at element zero of Versions array.
* V3. We receive instruction to update. We see if there is a child **Versions** property.  There is. We remove Versions property, and take copy of old version. We replace old entry with new one.  We insert old version at head of Versions array, then replace Versions into new entry.

See more (better quality) data here: https://stackoverflow.com/a/9743054/92441

We could silently retain these.  Or we could integrate it into the UI.

**Comment by Morphexe** [comment]
There is no need to overcomplicate, we already have a action to update entries.
So when we update a entrie we store the history of the file in side a revisions array.
#70-Store-history has this functionality, although there is no visual confirmation (unless you use redux dev tools to see, the revision is being stored, and a new field is introduced called, editAt : date).
