### ISSUE TITLE
Demote compass to member of category

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/narr-next#73]
@Morphexe has produced a compass widget.  It's very cool.

Currently it sits as a top-level member of the UI, like another category.  I would like to demote it to being a member of the General category.

So, we will have a new element in **UiConfig.js**.  Hmm, so, under "General" category, in addition to "entries", we will have "widgets" array.  This will contain one item "id":"Compass", priority:"High".

Then when we do the Category rendering, before we loop through Entries, we will loop through "widgets".  When we see the "Compass" widget we will insert the Compass component.

It will be larger than the entries, and  (very roughtly) look like this:
![screen shot 2018-03-30 at 07 51 20](https://user-images.githubusercontent.com/1108513/38127695-38eddee8-33ef-11e8-8568-e0fe92c47ff4.png)

**Comment by Morphexe** [comment]
this was also fixed with #78

**Comment by Morphexe** [comment]
@IanMayo I have updated the compass design and fixed a bug that wwas preventing the compass from updating after editing the values
