### ISSUE TITLE
Tidy repo

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/narr-next#92]
I'm pretty sure we've got a fair amount of unused code.

Could you go through and (carefully) delete it?

Our memory about how things work is better now than it will be in a few weeks.

**Comment by Morphexe** [comment]
I have a look into this, and AFAIK there actually isn't really that much-unused code, there might be something that I missed, but I think this removed everything that we don't use.

**Comment by IanMayo** [comment]
I saw src/Components/Filters.js  

I think the real one is in src/Components/LeftHand/Filters.js

Maybe that's the only unused one.

**Comment by Morphexe** [comment]
Correct! That's an unused file, removed on latest.
