### ISSUE TITLE
Shrink generator components

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/narr-next#99]
Here's the entry generator screen on my laptop:
<img width="558" alt="screen shot 2018-03-31 at 13 11 06" src="https://user-images.githubusercontent.com/1108513/38163029-1303e802-34e5-11e8-9ffe-29be781cccf9.png">

I have to shrink the text a long way to read the date.

Could you play with the layout?

**Comment by Morphexe** [comment]
@IanMayo  mind trying this new version ?

**Comment by IanMayo** [comment]
@Morphexe - in which branch can I trial this?

**Comment by Morphexe** [comment]
I think the fluid UI should have this already merged in.
I just reduced the size a bit .
